# LiteBot全局配置文件
# 务必使用Visual Studio Code、Sublime Text、NotePad++等专业编辑器进行修改
# 以下均为示例配置，用户可根据自己需要，按照示例配置进行修改

language: zh-cn #语言设置
debug_mode: true  #是否启用Debug模式，默认false

# QQ账户设置
qq_account:
  uin: 123456789 #QQ账号
  password: '56789!@3' #QQ密码，支持密码原文或密码的md5值。留空（默认）则使用扫码登录
  platform: 5  #登录平台设置（1:安卓手机(默认)，2:aPad，3:安卓手表，4:MacOS，5:iPad）

# QQ群聊设置，支持多个群聊
qq_group:
  903057105: #群号
    bind_server: [ 纯生存服,建筑创造服,空岛生存服 ] #该群绑定的服务器，支持一个或多个，与websocket_server配置项中的服务器名称对应。中括号内每个服务器名称用英文逗号隔开
    enable_chat_forward: true #是否启用聊天转发（群聊<->服务器、服务器<->服务器）功能，默认true
    enable_allowlist_helper: false #是否启用白名单助手功能
    admin: [ 987654321 ]  #机器人管理员的QQ号，支持一个或多个。中括号内每个QQ号用英文逗号隔开

  923387357:
    bind_server: [ 纯生存服,建筑创造服,空岛生存服 ]
    enable_chat_forward: false
    enable_allowlist_helper: true
    admin: [ 987654321 ]

# WebSocket服务器配置，支持多个服务器
# 每个服务器的配置与LLWS中的配置保持一致
websocket_server:
  纯生存服: #服务器名称
    enable: true  #是否启用该服务器
    wsaddr: ws://127.0.0.1:997  #WebSocket地址
    endpoint: /mc1  #WebSocket路径
    wspasswd: 1qaz@WSX  #WebSocket密钥
    reconnect_interval: 5 #断线重连间隔

  建筑创造服:
    enable: true
    wsaddr: ws://127.0.0.1:998
    endpoint: /mc2
    wspasswd: 1qaz@WSX
    reconnect_interval: 5

  空岛生存服:
    enable: true
    wsaddr: ws://127.0.0.1:999
    endpoint: /mc3
    wspasswd: 1qaz@WSX
    reconnect_interval: 5